### ISSUE TITLE
Casanova mobile v1.2>> Home page>> Company profile>> Designation

### ISSUE THREAD

**Issue by srinivasmudhiraj3** [gak112/CasanovaTesting#130]
**CURRENT OUTPUT:**- Here in **DESIGNATION** input, it is allowing numbers and special characters.

**EXPECTED OUTPUT**:- In **DESIGNATION** input, It should not allow numbers and special characters.

https://github.com/gak112/CasanovaTesting/assets/143584298/9b2fc0c2-1a64-4a5b-8895-e698988eeddc

**Comment by QSPaysys1** [comment]
Desgination has special chars
Example: UI/UX Designer, 3D Graphic Designer
