### ISSUE TITLE
Qspay mobile v1.6>> Products page>> Add product>> Select expiry date

### ISSUE THREAD

**Issue by srinivasmudhiraj3** [gak112/CasanovaTesting#209]
**CURRENT OUTPUT:-**  There is no Calendar icon for **SELECT EXPIRY DATE** input field.

**EXPECTED OUTPUT:-** The **SELECT EXPIRY DATE** input field should need a Calendar icon, that will helps to user very much.

![IMG_20231024_135252](https://github.com/gak112/CasanovaTesting/assets/143584298/708696d5-e615-4ade-8eec-81ebf92e02f6)

**Comment by QSPaysys1** [comment]
kept label as "Select Expiry Date"
