### ISSUE TITLE
Qspay mobile v1.6>> Promotions page>> Discount coupons>> Add coupons>> Placeholder missing for Expiry date

### ISSUE THREAD

**Issue by srinivasmudhiraj3** [gak112/CasanovaTesting#212]
**CURRENT OUTPUT**:-  There was no Placeholder and Calendar icon for **EXPIRY DATE** input field.

**EXPECTED OUTPUT:**- There should be a Placeholder and Calendar icon for **EXPIRY DATE** input field.

<img src="https://github.com/gak112/CasanovaTesting/assets/143584298/21d9e7c0-e7a3-485a-939a-9a34254c2d7c" width=400>

**Comment by QSPaysys1** [comment]
we kept label as "Expiry Date"
