### ISSUE TITLE
CASANOVA < store registration 

### ISSUE THREAD

**Issue by saigovindu9666** [gak112/CasanovaTesting#22]
Action : -Company name should be minimum 4 characters. 
Actual Output :- - In the company deatils not take the 2 or 3 CHARACTERS  started AT  4 characters but the company name is 3 charac
![MicrosoftTeams-image (4)](https://github.com/gak112/CasanovaTesting/assets/143585230/023fcd31-e888-4072-8179-13a009f7b6b5)
ters will not apply in form
Expected Output :- I want 2 or 3 characters will accepeted the  FORM DEATILES

**Comment by QSPaysys1** [comment]
company name should be minimum of 4 chars
