### ISSUE TITLE
store registration < designation 

### ISSUE THREAD

**Issue by saigovindu9666** [gak112/CasanovaTesting#26]
Action :- Designation only take the names
Actual Output :-  its takeing the numbers also
Expected Output : -  i want  application take names not the numbers
![MicrosoftTeams-image (6)](https://github.com/gak112/CasanovaTesting/assets/143585230/4865cf91-bcb9-4084-9392-66e534306f9b)

**Comment by QSPaysys1** [comment]
desgination has numbers and special chars
