### ISSUE TITLE
Casanova mobile>> Home page>> Company profile>> Designation

### ISSUE THREAD

**Issue by srinivasmudhiraj3** [gak112/CasanovaTesting#68]
### Expected output:- The **DESIGNATION** input field should not accept Numbers and Special characters, And there was a limit for characters in this input field.

https://github.com/gak112/CasanovaTesting/assets/143584298/2b2cc08c-0a79-42b0-ab63-d989ea94469b

**Comment by QSPaysys1** [comment]
there is a chance of numbers and special chars in desgination Input
Ex: UI/UX Designer, 3D Designer,

**Comment by srinivasmudhiraj3** [comment]
As you said that this is a Business portal application , not a job portal application like Dearjob @QSPaysys1
